name: Build & Deploy Angular App to GCP

on:
  push:
    branches:
      - dev

permissions:
  id-token: write     # 🔐 Pour OIDC
  contents: read

env:
  PROJECT_ID: petricator
  REGION: us-central11
  SERVICE_NAME: angular-app
  IMAGE: us-central1-docker.pkg.dev/petricator/petricator/petricator-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & build Angular app
        run: |
          npm ci
          npm run build -- --configuration=development

      - name: Auth to Google Cloud via OIDC
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: "projects/812288085862/locations/global/workloadIdentityPools/github-pool2/providers/github"
          service_account: "github-deploy-sa@petricator.iam.gserviceaccount.com"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --project $PROJECT_ID
