name: Deploy to Cloud Run (dev)

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authentifier avec GCP via OIDC
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: "projects/812288085862/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "github-deploy-sa@petricator.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Who am I
        run: gcloud auth list

      - name: Build Angular (dev)
        run: npm ci && npm run build

      - name: Build and Push Docker image
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/petricator-dev \
            --service-account=projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/812288085862-compute@developer.gserviceaccount.com \
            --gcs-log-dir=gs://petricator_cloudbuild/logs

      - name: Deploy to Cloud Run (dev)
        run: |
          gcloud run deploy petricator-dev \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/petricator-dev \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
